import { StyleSheet } from 'react-native'
import { colors, spacing, radius } from '../../../../theme'

export const etStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },

  // Tabs
  tabBar: {
    flexDirection: 'row',
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    marginBottom: spacing.xs,
    backgroundColor: colors.card,
    borderRadius: radius.lg,
    padding: 4,
    gap: 4,
  },
  tab: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: spacing.xs, paddingVertical: spacing.sm, borderRadius: radius.md,
  },
  tabActive: { backgroundColor: colors.primaryLight },
  tabText: { fontSize: 14, fontWeight: '600', color: colors.textMuted },
  tabTextActive: { color: colors.primary },

  // List
  listContent: { padding: spacing.lg, gap: spacing.md, paddingBottom: 96 },
  empty: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xl },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: colors.text },
  emptyText: { fontSize: 14, color: colors.textMuted, textAlign: 'center' },

  // Entry card
  entryCard: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  cardHeaderLeft: { flex: 1, gap: 2 },
  cardSituation: { fontSize: 15, fontWeight: '700', color: colors.text },
  cardDate: { fontSize: 12, color: colors.textMuted },
  cardActions: { flexDirection: 'row', gap: spacing.sm, marginLeft: spacing.sm },
  cardSuds: { gap: 4 },
  cardChips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  cardChip: {
    backgroundColor: colors.primary + '18',
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
  },
  cardChipText: { fontSize: 11, color: colors.primary, fontWeight: '500' },
  cardNotes: { fontSize: 13, color: colors.textMuted, lineHeight: 18 },

  // SudsBar
  sudsRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  sudsLabel: { fontSize: 12, color: colors.textMuted, width: 48 },
  sudsTrack: {
    flex: 1,
    height: 6,
    backgroundColor: colors.border,
    borderRadius: radius.full,
    overflow: 'hidden',
  },
  sudsFill: { height: '100%', borderRadius: radius.full },
  sudsValue: { fontSize: 13, fontWeight: '700', minWidth: 28, textAlign: 'right' },
  sudsPending: { fontSize: 13, color: colors.border, marginLeft: spacing.xs },

  // FAB
  fab: {
    position: 'absolute',
    bottom: spacing.xl,
    right: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.lg,
    height: 56,
    borderRadius: radius.full,
    backgroundColor: colors.primary,
    shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2, shadowRadius: 8, elevation: 6,
  },
  fabText: { color: colors.white, fontSize: 14, fontWeight: '700' },

  // Entry form
  entryHeaderBar: {
    paddingHorizontal: spacing.md, paddingVertical: spacing.sm,
    flexDirection: 'row', alignItems: 'center',
  },
  backBtn: {
    width: 44, height: 44, borderRadius: radius.full,
    alignItems: 'center', justifyContent: 'center',
  },
  entryContent: { padding: spacing.lg, gap: spacing.lg, paddingBottom: spacing.xl },
  section: { gap: spacing.sm },
  sectionLabel: {
    fontSize: 12, fontWeight: '700', color: colors.textMuted,
    textTransform: 'uppercase', letterSpacing: 0.8,
  },
  card: {
    backgroundColor: colors.card, borderRadius: radius.lg, padding: spacing.md,
    gap: spacing.md,
    borderWidth: 1, borderColor: colors.border,
  },

  // Situation picker
  toggle: { flexDirection: 'row', gap: spacing.xs },
  toggleBtn: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  toggleBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  toggleText: { fontSize: 13, color: colors.textMuted },
  toggleTextActive: { color: colors.white, fontWeight: '600' },
  catalogueList: { gap: spacing.xs },
  catalogueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    padding: spacing.sm,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  catalogueItemSelected: { borderColor: colors.primary, backgroundColor: colors.primary + '0F' },
  catalogueItemLabel: { flex: 1, fontSize: 14, color: colors.text },
  catalogueItemLabelSelected: { color: colors.primary, fontWeight: '600' },
  catalogueEmpty: { fontSize: 13, color: colors.textMuted, textAlign: 'center', paddingVertical: spacing.sm },
  freeInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.background,
    textAlignVertical: 'top',
    minHeight: 64,
  },

  // SUDs picker (entry form)
  sudsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  sudsHeaderLeft: { flex: 1, gap: 2 },
  sudsHeaderLabel: { fontSize: 14, fontWeight: '700', color: colors.text },
  sudsHeaderHint: { fontSize: 12, color: colors.textMuted },
  sudsValueBox: { flexDirection: 'row', alignItems: 'baseline', gap: 2 },
  sudsValueBig: { fontSize: 22, fontWeight: '800' },
  sudsValueNull: { fontSize: 22, fontWeight: '800', color: colors.textMuted },
  sudsValueMax: { fontSize: 12, color: colors.textMuted },
  skipBtn: { alignSelf: 'flex-start', paddingVertical: 4 },
  skipText: { fontSize: 12, color: colors.textMuted, textDecorationLine: 'underline' },

  // Strategies
  stratHint: { fontSize: 12, color: colors.textMuted },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  chipActive: { borderColor: colors.primary, backgroundColor: colors.primary + '14' },
  chipText: { fontSize: 13, color: colors.textMuted },
  chipTextActive: { color: colors.primary, fontWeight: '600' },
  customStratInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.background,
  },

  // Notes
  notesInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.background,
    minHeight: 72,
    textAlignVertical: 'top',
  },

  // Save / delete
  saveBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: spacing.sm, backgroundColor: colors.primary, borderRadius: radius.md,
    paddingVertical: spacing.sm + 4,
  },
  btnDisabled: { opacity: 0.6 },
  saveBtnText: { color: colors.white, fontSize: 16, fontWeight: '700' },
  deleteBtn: { alignItems: 'center', paddingVertical: spacing.sm },
  deleteBtnText: { color: colors.danger, fontSize: 14, fontWeight: '600' },

  // Situations panel
  panelContent: { padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xl },
  panelCard: {
    backgroundColor: colors.card,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm,
  },
  panelTitle: { fontSize: 14, fontWeight: '700', color: colors.text },
  panelHint: { fontSize: 13, color: colors.textMuted, lineHeight: 18 },
  panelAddRow: { flexDirection: 'row', gap: spacing.sm },
  panelInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 8,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.background,
  },
  panelAddBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  panelEmpty: { fontSize: 13, color: colors.border, textAlign: 'center', paddingVertical: spacing.sm },
  panelList: { gap: spacing.xs },
  panelItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colors.background,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  panelItemLabel: { flex: 1, fontSize: 13, color: colors.text },
})
