import { StyleSheet } from 'react-native'
import { colors, spacing, radius } from '@theme'

export const styles = StyleSheet.create({
  questionnaireContainer: { gap: spacing.md },
  instructionBlock: {
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 4,
  },
  instructionText: { fontSize: 14, color: colors.text, lineHeight: 20 },
  legendRow:      { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  legendItem:     { alignItems: 'center', flex: 1 },
  legendNum:      { fontSize: 15, fontWeight: '700', color: colors.primary },
  legendLabel:    { fontSize: 10, color: colors.textMuted, textAlign: 'center', marginTop: 2 },
  warningBlock:   { flexDirection: 'row', alignItems: 'flex-start', gap: 8, backgroundColor: '#FFFBEB', borderWidth: 1, borderColor: '#FDE68A', borderRadius: 8, padding: spacing.sm },
  warningText:    { fontSize: 13, color: '#92400E', flex: 1, lineHeight: 18 },
  questionsBlock: { gap: spacing.sm },
  sectionHeader:  { paddingVertical: 6, paddingHorizontal: 2, borderBottomWidth: 1, borderBottomColor: colors.border, marginTop: 4 },
  sectionLabel:   { fontSize: 13, fontWeight: '700', color: colors.textMuted, textTransform: 'uppercase', letterSpacing: 0.5 },
  questionCard:   { backgroundColor: colors.card, borderRadius: 10, padding: spacing.md, borderWidth: 1, borderColor: colors.border, gap: spacing.sm },
  questionText:   { fontSize: 14, color: colors.text, lineHeight: 20 },
  questionNum:    { fontWeight: '700', color: colors.primary },
  footerText:     { fontSize: 12, color: colors.textMuted, flex: 1, lineHeight: 17 },
  infoBox:        { flexDirection: 'row', gap: 6, alignItems: 'flex-start', marginTop: 12, padding: 10, backgroundColor: '#F3F4F6', borderRadius: 8 },
  supplementaryBlock: { gap: spacing.sm },
  supplementaryTitle: {
    fontSize: 13, fontWeight: '700', color: colors.textMuted,
    textTransform: 'uppercase', letterSpacing: 0.5, paddingHorizontal: 2,
  },
  extraCard: {
    backgroundColor: colors.card, borderRadius: 10, padding: spacing.md,
    borderWidth: 1, borderColor: colors.border, gap: spacing.sm,
  },
  extraLabel: { fontSize: 14, color: colors.text, lineHeight: 20 },
  numberInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  numberInput: {
    borderWidth: 1.5, borderColor: colors.border, borderRadius: 8,
    paddingVertical: 8, paddingHorizontal: 12, fontSize: 16, color: colors.text,
    width: 70, textAlign: 'center',
  },
  numberInputUnit: { fontSize: 16, color: colors.textMuted },
  textInput: {
    borderWidth: 1.5, borderColor: colors.border, borderRadius: 8,
    paddingVertical: 8, paddingHorizontal: 12, fontSize: 14, color: colors.text,
  },
  sliderCard:      { backgroundColor: colors.card, borderRadius: 10, padding: spacing.md, borderWidth: 1, borderColor: colors.border, gap: spacing.sm },
  sliderHeader:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sliderLabelRow:  { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  sliderLabel:     { fontSize: 15, fontWeight: '600' },
  sliderValue:     { fontSize: 24, fontWeight: '800', minWidth: 32, textAlign: 'right' },
  sliderPips:      { flexDirection: 'row', gap: 4 },
  sliderPip:       { flex: 1, aspectRatio: 1, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
  sliderPipText:   { fontSize: 11, fontWeight: '500', color: colors.textMuted },
  sliderPipTextSelected: { color: colors.white, fontWeight: '700' },
  sliderHints:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sliderHint:      { fontSize: 11, color: colors.textMuted },
  sliderHintMid:   { fontSize: 11, fontWeight: '700', textAlign: 'center' },
})
