import { StyleSheet } from 'react-native'
import { colors, spacing, radius } from '../../../../../theme'

export const styles = StyleSheet.create({
  container:         { flex: 1, backgroundColor: colors.background },
  center:            { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
  // ── List
  listContent:       { padding: spacing.lg, paddingBottom: spacing.xl, gap: spacing.xs },
  ctaContainer:      { gap: spacing.sm, marginBottom: spacing.md },
  ctaCard: {
    backgroundColor: colors.primary, borderRadius: radius.lg,
    padding: spacing.md,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2,
  },
  monthCard: {
    backgroundColor: colors.card, borderRadius: radius.lg,
    padding: spacing.md, borderWidth: 1, borderColor: colors.border,
  },
  ctaRow:            { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  ctaTexts:          { flex: 1 },
  ctaTitle:          { fontSize: 17, fontWeight: '700', color: colors.white },
  ctaSubtitle:       { fontSize: 13, color: 'rgba(255,255,255,0.75)', marginTop: 2 },
  monthBtnText:      { flex: 1, fontSize: 15, fontWeight: '600', color: colors.primary },
  chevron:           { fontSize: 22, color: colors.textMuted, fontWeight: '300' },
  chevronWhite:      { fontSize: 22, color: colors.white, fontWeight: '300' },
  listHeader: {
    fontSize: 13, fontWeight: '700', color: colors.textMuted,
    textTransform: 'uppercase', letterSpacing: 0.8,
    marginBottom: spacing.sm, marginTop: spacing.sm,
  },
  dayRow: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.md,
    paddingVertical: spacing.sm + 4, paddingHorizontal: spacing.md,
    borderRadius: radius.md, marginBottom: spacing.xs, backgroundColor: colors.card,
  },
  dayRowFilled:      { borderLeftWidth: 3, borderLeftColor: colors.success },
  dot:               { width: 10, height: 10, borderRadius: 5 },
  dotFilled:         { backgroundColor: colors.success },
  dotEmpty:          { backgroundColor: colors.border },
  dayInfo:           { flex: 1 },
  dayDate:           { fontSize: 15, fontWeight: '500', color: colors.textMuted },
  dayDateFilled:     { color: colors.text, fontWeight: '600' },
  entryDetails:      { marginTop: 2, gap: 1 },
  entryMeta:         { fontSize: 13, color: colors.textMuted },
  entryMetaStrong:   { fontWeight: '600', color: colors.primary },
  emptyDay:          { fontSize: 13, color: colors.border, fontStyle: 'italic', marginTop: 2 },
  starsRow:          { flexDirection: 'row', gap: 2, marginTop: 2 },
  // ── Month
  monthNav: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.sm,
    paddingHorizontal: spacing.md, paddingVertical: spacing.sm,
    backgroundColor: colors.card, borderBottomWidth: 1, borderBottomColor: colors.border,
  },
  navBtn:            { padding: spacing.xs },
  navBtnDisabled:    { opacity: 0.3 },
  monthTitle: {
    flex: 1, fontSize: 17, fontWeight: '700',
    color: colors.text, textAlign: 'center', textTransform: 'capitalize',
  },
  monthContent:      { padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xl },
  calendarCard: {
    backgroundColor: colors.card, borderRadius: radius.lg, padding: spacing.md,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2,
    gap: 4,
  },
  calendarHeader:    { flexDirection: 'row', justifyContent: 'space-between' },
  calendarRow:       { flexDirection: 'row', justifyContent: 'space-between' },
  weekday: {
    flex: 1, textAlign: 'center', fontSize: 11, fontWeight: '700',
    color: colors.textMuted, textTransform: 'uppercase', paddingBottom: spacing.xs,
  },
  calendarCell: {
    flex: 1, aspectRatio: 1,
    alignItems: 'center', justifyContent: 'center', padding: 2,
  },
  dayDot: {
    width: '85%', aspectRatio: 1, borderRadius: radius.full,
    alignItems: 'center', justifyContent: 'center',
  },
  dayDotToday:       { borderWidth: 2, borderColor: colors.primary },
  dayNum:            { fontSize: 12, fontWeight: '500', color: colors.textMuted },
  dayNumFilled:      { color: colors.white, fontWeight: '700' },
  dayNumFuture:      { color: colors.border },
  nightmareBadge: {
    position: 'absolute', top: 0, right: 0, width: 12, height: 12,
    borderRadius: 6, backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center', justifyContent: 'center',
  },
  sectionTitle: {
    fontSize: 12, fontWeight: '700', color: colors.textMuted,
    textTransform: 'uppercase', letterSpacing: 0.8, marginTop: spacing.xs,
  },
  statsGrid:         { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  statCard: {
    flex: 1, minWidth: '45%', backgroundColor: colors.card,
    borderRadius: radius.lg, padding: spacing.md, alignItems: 'center',
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2,
  },
  statValue:         { fontSize: 26, fontWeight: '800', color: colors.primary },
  statLabel:         { fontSize: 13, color: colors.textMuted, marginTop: 2, textAlign: 'center' },
  legendCard: {
    backgroundColor: colors.card, borderRadius: radius.lg, padding: spacing.md,
    gap: spacing.sm,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2,
  },
  legendRow:         { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  legendDot:         { width: 12, height: 12, borderRadius: 6 },
  legendLabel:       { fontSize: 13, color: colors.textMuted },
  // ── Entry
  entryHeaderBar: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.sm,
    paddingHorizontal: spacing.md, paddingVertical: spacing.sm,
    backgroundColor: colors.card, borderBottomWidth: 1, borderBottomColor: colors.border,
  },
  backBtn:           { padding: spacing.xs },
  entryHeaderTitle:  { flex: 1, gap: 2 },
  entryContent:      { padding: spacing.lg, gap: spacing.lg, paddingBottom: spacing.xl },
  dateLabel: {
    fontSize: 11, fontWeight: '600', color: colors.primary,
    textTransform: 'uppercase', letterSpacing: 0.5,
  },
  dateValue:         { fontSize: 17, fontWeight: '700', color: colors.text },
  section:           { gap: spacing.sm },
  sectionLabel: {
    fontSize: 12, fontWeight: '700', color: colors.textMuted,
    textTransform: 'uppercase', letterSpacing: 0.8,
  },
  card: {
    backgroundColor: colors.card, borderRadius: radius.lg, padding: spacing.md,
    gap: spacing.md,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2,
  },
  divider:           { height: 1, backgroundColor: colors.border },
  timeFieldGroup:    { gap: spacing.xs },
  fieldLabel:        { fontSize: 14, fontWeight: '600', color: colors.text },
  timeBtn: {
    backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border,
    borderRadius: radius.md, paddingHorizontal: spacing.md, paddingVertical: spacing.sm + 4,
    flexDirection: 'row', alignItems: 'center', gap: spacing.sm,
  },
  timeValue:         { fontSize: 22, fontWeight: '700', color: colors.primary },
  timeHint:          { fontSize: 13, color: colors.textMuted, marginLeft: spacing.xs },
  confirmBtn: {
    backgroundColor: colors.primaryLight, borderRadius: radius.md,
    padding: spacing.sm, alignItems: 'center', marginTop: spacing.xs,
  },
  confirmBtnText:    { color: colors.primary, fontWeight: '600' },
  minutesRow:        { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  minutesInput: {
    width: 72, fontSize: 28, fontWeight: '700', color: colors.primary,
    backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border,
    borderRadius: radius.md, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs,
    textAlign: 'center',
  },
  minutesUnit:       { fontSize: 15, color: colors.textMuted },
  minutesConv:       { fontSize: 15, fontWeight: '600', color: colors.primary },
  counterRow:        { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  counterBtn: {
    width: 44, height: 44, borderRadius: radius.md, backgroundColor: colors.background,
    borderWidth: 1, borderColor: colors.border,
    justifyContent: 'center', alignItems: 'center',
  },
  counterBtnDisabled:{ opacity: 0.4 },
  counterBtnText:    { fontSize: 24, fontWeight: '300', color: colors.text, lineHeight: 28 },
  counterValue:      { fontSize: 28, fontWeight: '700', color: colors.text, minWidth: 40, textAlign: 'center' },
  toggleRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: spacing.md,
  },
  toggleLeft:        { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  toggleLabel:       { fontSize: 15, fontWeight: '500', color: colors.text },
  switchTrack: {
    width: 48, height: 28, borderRadius: radius.full,
    backgroundColor: colors.border, padding: 2, justifyContent: 'center',
  },
  switchTrackOn:     { backgroundColor: colors.danger },
  switchThumb: {
    width: 24, height: 24, borderRadius: radius.full,
    backgroundColor: colors.white, alignSelf: 'flex-start',
  },
  switchThumbOn:     { alignSelf: 'flex-end' },
  starsBig:          { flexDirection: 'row', gap: spacing.sm },
  qualityLabel:      { fontSize: 14, color: colors.textMuted, fontStyle: 'italic' },
  notesInput: {
    fontSize: 15, color: colors.text, minHeight: 90, lineHeight: 22,
  },
  seCard: {
    borderWidth: 2, borderRadius: radius.lg, padding: spacing.md,
    backgroundColor: colors.card, gap: spacing.xs,
  },
  seRow:             { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  seTitle:           { flex: 1, fontSize: 15, fontWeight: '600', color: colors.text },
  seScore:           { fontSize: 24, fontWeight: '800' },
  saveBtn: {
    backgroundColor: colors.primary, borderRadius: radius.lg, paddingVertical: spacing.md,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm,
  },
  saveBtnText:       { fontSize: 16, fontWeight: '700', color: colors.white },
  btnDisabled:       { opacity: 0.6 },
  deleteBtn: {
    borderRadius: radius.lg, paddingVertical: spacing.md,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: colors.card, borderWidth: 1, borderColor: colors.danger,
  },
  deleteBtnText:     { fontSize: 15, fontWeight: '600', color: colors.danger },
})
